version: '3'

services:
  ch-worker:
    build:
      context: .
      dockerfile: DockerfileGPU_ch
    image: image-ocr-worker-ch
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
  ch-server:
    image: image-ocr-server
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    network_mode: "host"
    restart: always
    environment:
      - "port=8000"
      - "worker_port=8800"
      - "app_name=image-ocr-server-ch"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    volumes:
      - /tmp/image-ocr-service-ch:/app/logs