version: '3'

services:
  ar-worker:
    build:
      context: .
      dockerfile: DockerfileGPU_ar
    image: image-ocr-worker-ar
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
  ar-server:
    image: image-ocr-server
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003" ]
    network_mode: "host"
    restart: always
    environment:
      - "port=8003"
      - "worker_port=8803"
      - "app_name=image-ocr-server-ar"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    volumes:
      - /tmp/image-ocr-service-ar:/app/logs