version: '3'

services:
  hi-worker:
    build:
      context: .
      dockerfile: DockerfileGPU_hi
    image: image-ocr-worker-hi
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
  hi-server:
    image: image-ocr-server
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001" ]
    network_mode: "host"
    restart: always
    environment:
      - "port=8001"
      - "worker_port=8801"
      - "app_name=image-ocr-server-hi"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    volumes:
      - /tmp/image-ocr-service-hi:/app/logs
